spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/test

  jpa:
    properties:
      hibernate:
        ddl-auto: create
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always